import {
  MistralLogo,
  OpenAILogo,
  GeminiLogo,
  AwsLogo,
  AzureLogo,
  AnthropicLogo,
  GroqLogo,
  FireworksLogo,
  DeepseekLogo,
  CohereLogo,
  OllamaLogo,
  XaiLogo,
  AgnoIcon,
  RPLogoIcon,
  UserIcon,
  AgentIcon,
  SheetIcon,
  NextjsTag,
  ShadcnTag,
  TailwindTag,
  AgnoTag,
  ReasoningIcon,
  ReferencesIcon,
  // App icons
  FigmaIcon,
  SlackIcon,
  NotionIcon,
  GithubIcon,
  LinearIcon
} from './custom-icons'
import { IconTypeMap } from './types'
import {
  RefreshCw,
  Edit,
  Save,
  X,
  ArrowDown,
  SendIcon,
  Download,
  HammerIcon,
  Check,
  ChevronDown,
  ChevronUp,
  Trash,
  // Agent icons
  Target,
  FileText,
  Search,
  ImageIcon,
  Palette,
  Bug,
  Globe,
  Sparkles,
  Presentation,
  Rocket,
  TrendingUp,
  BookOpen,
  MessageCircle,
  Users,
  Calendar
} from 'lucide-react'

import { PlusIcon } from '@radix-ui/react-icons'

export const ICONS: IconTypeMap = {
  // Provider logos
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  agno: AgnoIcon,
  'rp-logo': RPLogoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  tailwind: TailwindTag,
  reasoning: ReasoningIcon,
  'agno-tag': AgnoTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  x: X,
  'arrow-down': ArrowDown,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'plus-icon': PlusIcon,
  references: ReferencesIcon,
  trash: Trash,
  // App icons
  figma: FigmaIcon,
  slack: SlackIcon,
  notion: NotionIcon,
  github: GithubIcon,
  linear: LinearIcon,
  // Agent keyword icons (Lucide)
  target: Target,
  'file-text': FileText,
  search: Search,
  image: ImageIcon,
  palette: Palette,
  bug: Bug,
  globe: Globe,
  sparkles: Sparkles,
  presentation: Presentation,
  rocket: Rocket,
  'trending-up': TrendingUp,
  'book-open': BookOpen,
  'message-circle': MessageCircle,
  users: Users,
  calendar: Calendar
}
